#!/usr/bin/python

import feedparser
import requests
import json
import argparse


#Fetch Music meditation generated by rss.ap from youtube

rss_music = 'https://rss.app/feeds/jAOa1YTPKxhIhlZz.xml'
feed_music = feedparser.parse(rss_music)
first_music = feed_music.entries[0].link
def print_news(first_music):
    return first_music

#Fetch Media Releases from the Minister for Mental Health

rss_health = 'https://www.health.nsw.gov.au/_layouts/15/feed.aspx?xsl=1&web=/news&page=d6828794-f20b-4d11-839e-9edd75d483ff&wp=cf6e281c-d6f6-4c22-b78f-e6890eccd5fb&pageurl=/news/Pages/rss-minister-for-mental-health.aspx'
feed_health = feedparser.parse(rss_health)
first_health = feed_health.entries[0].link
def print_news(first_health):
    return first_health


# Fetch the iTnews RSS feed
rss_news = 'https://www.itnews.com.au/RSS/rss.ashx'
feed = feedparser.parse(rss_news)
first_news = feed.entries[0].link
def print_news(first_news):
    return first_news

# Send a bot message
def send_slack_message(payload, webhook):
    return requests.post(webhook, json.dumps(payload))

webhook = "https://hooks.slack.com/services/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"
payload = {"text": f"Here is the NewsLink for today! Enjoy it! {first_news}"}
send_slack_message(payload, webhook)






